# Generated by Django 3.2.14 on 2023-02-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_library', '0003_auto_20230202_1410'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='can_borrow',
            field=models.BooleanField(default=False, verbose_name='Can borrow a book'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_loan',
            field=models.BooleanField(default=False, verbose_name='Can loan a book'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_sell',
            field=models.BooleanField(default=False, verbose_name='Can sell a book'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date joined'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
