# Generated by Django 3.2.14 on 2023-02-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230202_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(default='admin2019', max_length=255),
            preserve_default=False,
        ),
    ]
