# Generated by Django 3.2.9 on 2022-05-17 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220517_2206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Librarian',
        ),
    ]
