# Generated by Django 4.0.1 on 2022-01-28 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user_location_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='book_title')),
                ('author', models.CharField(max_length=255, verbose_name='author')),
                ('date_acquired', models.DateField(verbose_name='date_acquired')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='book_owner', to='users.user')),
            ],
        ),
    ]
