# This is the main configuration file for the application.
# https://www.playframework.com/documentation/latest/ConfigFile

# Default database configuration
# Connect to playdb as playdbuser
#MySQL connection properties
ebean.default="models.*"
play.db {
  config = "db"
  default = "default"

  #pool = bonecp
  #prototype {
    # Sets a fixed JDBC connection pool size of 50
    #hikaricp.minimumIdle = 50
    #hikaricp.maximumPoolSize = 50
  #}
}
play.evolutions{
  default.enabled = true
}
db{
  default.driver=com.mysql.jdbc.Driver
  default.url="jdbc:mysql://127.0.0.1:3306/laebrariDB?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8"
  default.username = root
  default.password = "root"
  default.logSql = true
  default.jndiName= DefaultDS
  default.host="localhost"
}




  #Configuring the CustomExecutionContext
  fixedConnectionPool = 9
  database.dispatcher {
    executor = "thread-pool-executor"
    throughput = 1
    thread-pool-executor {
      fixed-pool-size = ${fixedConnectionPool}
    }
  }
