# Generated by Django 4.0.1 on 2022-03-11 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_remove_user_location_remove_user_phone_user_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='book_title')),
                ('author', models.CharField(max_length=255, verbose_name='author')),
                ('date_acquired', models.DateField(verbose_name='date_acquired')),
                ('genre', models.CharField(blank=True, max_length=255, null=True)),
                ('available_to_borrow', models.BooleanField(default=False)),
                ('available_to_sell', models.BooleanField(default=False)),
                ('private_library', models.BooleanField(default=True)),
                ('borrowing_price', models.IntegerField()),
                ('selling_price', models.FloatField()),
                ('book_condition', models.CharField(blank=True, max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='book_owner', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('lender_rating', models.IntegerField()),
                ('borrower_rating', models.IntegerField()),
                ('seller_rating', models.IntegerField()),
                ('overall_rating', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='collection', to='user_library.book')),
                ('library_owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='librarian', to='user_library.librarian')),
            ],
        ),
        migrations.CreateModel(
            name='BookTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[['borrow', 'Borrow'], ['sell', 'Sell']], max_length=255)),
                ('transaction_date', models.DateField(auto_now=True, verbose_name='date_borrowed')),
                ('return_date', models.DateField(verbose_name='return_date')),
                ('book_transacted', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='book_transacted', to='user_library.book')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='borrower', to='users.user')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='buyer', to='users.user')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_owner', to='users.user')),
            ],
        ),
    ]
