# Generated by Django 3.2.14 on 2023-02-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='book title')),
                ('author', models.CharField(max_length=255, verbose_name='author')),
                ('memo', models.CharField(max_length=255, verbose_name='memo')),
                ('isbn', models.CharField(max_length=255, verbose_name='isbn')),
                ('date_acquired', models.DateField(verbose_name='date acquired')),
                ('genre', models.CharField(max_length=255)),
                ('available_to_borrow', models.BooleanField(default=False)),
                ('available_to_sell', models.BooleanField(default=False)),
                ('borrowing_price', models.IntegerField()),
                ('selling_price', models.FloatField()),
                ('book_condition', models.CharField(choices=[('NEW', 'NEW'), ('OLD', 'OLD'), ('GOOD CONDITION', 'GOOD CONDITION')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BookTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('LOAN', 'LOAN'), ('SELL', 'SELL')], max_length=255, verbose_name='Transaction Type')),
                ('transaction_date', models.DateField(auto_now=True, verbose_name='transaction_date')),
                ('end_of_transaction', models.DateField(blank=True, null=True, verbose_name='return_date')),
            ],
        ),
        migrations.CreateModel(
            name='UserLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='Kenya', max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(default='None', max_length=255)),
                ('date_established', models.DateTimeField(blank=True, null=True)),
                ('established_by', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, choices=[('PRIVATE', 'PRIVATE'), ('PUBLIC', 'PUBLIC'), ('UNLISTED', 'UNLISTED')], default=('PRIVATE', 'PRIVATE'), max_length=255, null=True)),
            ],
        ),
    ]
