# Generated by Django 3.2.14 on 2023-03-02 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_library', '0003_auto_20230202_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=255)),
                ('location', models.CharField(default='Kenya', max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_established', models.DateField(blank=True, null=True)),
                ('established_by', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, choices=[('PRIVATE', 'PRIVATE'), ('PUBLIC', 'PUBLIC'), ('UNLISTED', 'UNLISTED')], default=('PRIVATE', 'PRIVATE'), max_length=255, null=True)),
                ('librarian', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='librarians', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'location')},
            },
        ),
    ]
