# Generated by Django 3.2.9 on 2022-05-25 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile'),
        ('user_library', '0004_auto_20220524_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_established', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('PRIVATE', 'PRIVATE'), ('PUBLIC', 'PUBLIC'), ('UNLISTED', 'UNLISTED')], max_length=255, null=True)),
                ('established_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='library_owner', to='users.profile')),
                ('librarian', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='librarian', to='users.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
