# Generated by Django 3.2.14 on 2023-10-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_library', '0005_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookGenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(default='None', max_length=255)),
            ],
            options={
                'ordering': ['genre'],
            },
        ),
        migrations.AlterField(
            model_name='book',
            name='book_condition',
            field=models.CharField(choices=[('NEW', 'NEW'), ('USED', 'USED')], max_length=255),
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(related_name='books', to='user_library.BookGenres'),
        ),
    ]
