# Generated by Django 3.2.9 on 2022-05-26 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile'),
        ('user_library', '0005_auto_20220525_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlibrary',
            name='established_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userlibrary',
            name='librarian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='librarians', to='users.profile'),
        ),
    ]
