# Generated by Django 3.2.9 on 2022-07-05 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_user'),
        ('user_library', '0006_auto_20220526_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='book_title')),
                ('author', models.CharField(max_length=255, verbose_name='author')),
                ('date_acquired', models.DateField(verbose_name='date_acquired')),
                ('genre', models.CharField(blank=True, max_length=255, null=True)),
                ('available_to_borrow', models.BooleanField(default=False)),
                ('available_to_sell', models.BooleanField(default=False)),
                ('borrowing_price', models.IntegerField()),
                ('selling_price', models.FloatField()),
                ('book_condition', models.CharField(blank=True, max_length=255)),
                ('library', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='library_book', to='user_library.userlibrary')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='book_owner', to='users.profile')),
            ],
        ),
    ]
