# Generated by Django 3.2.9 on 2022-07-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_library', '0007_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_condition',
            field=models.CharField(blank=True, choices=[('NEW', 'NEW'), ('OLD', 'OLD'), ('GOOD CONDITION', 'GOOD CONDITION')], max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_acquired',
            field=models.DateField(verbose_name='date acquired'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255, verbose_name='book title'),
        ),
    ]
