# Generated by Django 3.2.9 on 2022-07-05 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_user'),
        ('user_library', '0008_auto_20220705_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='library_book', to='user_library.userlibrary'),
        ),
        migrations.AlterField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='book_owner', to='users.profile'),
        ),
    ]
