# Generated by Django 3.2.9 on 2022-07-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_library', '0009_auto_20220705_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='rtuuertuet', max_length=255, verbose_name='author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='memo',
            field=models.CharField(default='reituout', max_length=255, verbose_name='author'),
            preserve_default=False,
        ),
    ]
