# Generated by Django 3.2.9 on 2022-07-14 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_library', '0010_auto_20220705_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[['borrow', 'Borrow'], ['buy', 'Buy']], max_length=255)),
                ('transaction_date', models.DateField(auto_now=True, verbose_name='date_borrowed')),
                ('return_date', models.DateField(verbose_name='return_date')),
                ('book_transacted', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='book_transacted', to='user_library.book')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='borrower', to=settings.AUTH_USER_MODEL)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='buyer', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
