# Generated by Django 3.2.9 on 2022-07-14 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_user'),
        ('user_library', '0011_booktransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktransaction',
            name='owner',
        ),
        migrations.AddField(
            model_name='booktransaction',
            name='library',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_owner', to='user_library.userlibrary'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booktransaction',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='borrower', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='booktransaction',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='buyer', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='booktransaction',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='return_date'),
        ),
    ]
