# Generated by Django 3.2.9 on 2022-08-04 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_library', '0013_auto_20220802_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booktransaction',
            old_name='return_date',
            new_name='end_of_transaction',
        ),
        migrations.RenameField(
            model_name='booktransaction',
            old_name='transactor',
            new_name='patron',
        ),
        migrations.AlterField(
            model_name='booktransaction',
            name='transaction_date',
            field=models.DateField(auto_now=True, verbose_name='transaction_date'),
        ),
        migrations.AlterField(
            model_name='booktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('LOAN', 'LOAN'), ('SELL', 'SELL')], max_length=255),
        ),
    ]
