# Generated by Django 3.2.9 on 2022-08-08 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_user'),
        ('user_library', '0015_auto_20220808_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktransaction',
            name='end_of_transaction',
            field=models.DateField(null=True, verbose_name='return_date'),
        ),
        migrations.AlterField(
            model_name='booktransaction',
            name='patron',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='borrower', to='users.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('LOAN', 'LOAN'), ('SELL', 'SELL')], max_length=255, verbose_name='Transaction Type'),
        ),
    ]
