# Generated by Django 3.2.9 on 2022-08-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_library', '0017_alter_booktransaction_end_of_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktransaction',
            name='end_of_transaction',
            field=models.DateField(blank=True, null=True, verbose_name='return_date'),
        ),
    ]
