# Generated by Django 3.2.9 on 2022-09-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_library', '0018_alter_booktransaction_end_of_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlibrary',
            name='location',
            field=models.CharField(default='Kenya', max_length=255),
        ),
        migrations.AlterField(
            model_name='userlibrary',
            name='name',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='userlibrary',
            unique_together={('name', 'location')},
        ),
    ]
