# Generated by Django 3.2.9 on 2022-09-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_library', '0021_alter_userlibrary_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=255, verbose_name='isbn'),
        ),
        migrations.AlterField(
            model_name='book',
            name='memo',
            field=models.CharField(max_length=255, verbose_name='memo'),
        ),
        migrations.AlterField(
            model_name='userlibrary',
            name='type',
            field=models.CharField(blank=True, choices=[('PRIVATE', 'PRIVATE'), ('PUBLIC', 'PUBLIC'), ('UNLISTED', 'UNLISTED')], default=('PRIVATE', 'PRIVATE'), max_length=255, null=True),
        ),
    ]
