# Generated by Django 3.2.9 on 2022-10-01 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_user'),
        ('user_library', '0022_auto_20220930_1137'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'author')},
        ),
        migrations.CreateModel(
            name='TransactionRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(verbose_name='rating')),
                ('rating_date', models.DateTimeField(auto_now=True, verbose_name='rating_date')),
                ('rated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rated_by', to='users.profile')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='user_library.booktransaction')),
            ],
        ),
    ]
