# This is the main configuration file for the application.
# https://www.playframework.com/documentation/latest/ConfigFile

# Default database configuration
# Connect to playdb as playdbuser
db.default.driver = com.mysql.jdbc.Driver
db.default.url="jdbc:mysql://localhost/playdb"
db.default.username = playdbuser
db.default.password = "mypassword"