# Generated by Django 4.0.1 on 2022-01-28 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user_location_user_phone'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_borrowed', models.DateField(auto_now=True, verbose_name='date_borrowed')),
                ('return_date', models.DateField(verbose_name='return_date')),
                ('book_borrowed', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='book_borrowed', to='books.book')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='borrower', to='users.user')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lender', to='users.user')),
            ],
        ),
    ]
